### ISSUE TITLE
habitat environment setup problems

### ISSUE THREAD

**Issue by molnarszilard** [RozDavid/semantic_mapping#2]
I was trying to create the conda environment for the habitat sim, but I have run into some problems.

First of all there are two habitat_env.yml files (semantic_mapping/config/habitat_env.yml and semantic_mapping/habitat/config/habitat_env.yml), they seem to be different, and I don't know which one to use. Although I had the same problems with each of them:

1. the version for habitat (0.1.7) and habitat-sim (0.1.7) are not found. I could resolve this issue by removing the version number from habitat, and moved habitat-sim (without version number) from the pip packages to the conda packages in the yml file.

2. After this, when I tried to create the environment it stalled at 'Installing pip dependencies:' 
    Then I separated the yml file into two: one for creating the environment with the conda packages, and another one with the pip dependencies. The environment was created without any problem, but when it run 'pip install -r habitat_pip.txt' there were some errors (supposedly the same errors, that were given previously at the environment setup, but they were not logged):
Actually it seems to install all the pip dependencies, but then it tries to match the different versions of packages.
a. the first problem is that it tries to install the couchdbkit package, which is not supported in python3. 
(there is also an error: NameError: name 'file' is not defined, where file is a function, which is also not supported in python3).
b. The previous error did not killed the pip install, so I left it for the night to see if it succeeds, but it stalled at:
INFO: pip is looking at multiple versions of python-dateutil to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

At this point I don't know how to proceed. Any advices?

**Comment by molnarszilard** [comment]
In the habitat folder I downloaded the two habitat repos:
  git clone https://github.com/facebookresearch/habitat-sim.git
  git clone https://github.com/facebookresearch/habitat-lab.git
then run 
  bash setup.sh
seems like did the trick (but it took about 2hours)

**Comment by RozDavid** [comment]
Thanks for the input! Fixed it with the submodules and source script in 83e7abe.
